### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by johnpbloch** [comment]
Thanks for your interest in contributing. This repository doesn't accept contributions for changes to the upstream codebase since it's automatically synced from the official WordPress repository.

**Comment by Piterden** [comment]
If so. You need to think about changing this data on fly during syncing. Why do not you do so?

**Comment by johnpbloch** [comment]
Because it's a waste of my time. It adds nothing of value to this repository and it's something I will have to maintain and support indefinitely.

**Comment by Piterden** [comment]
How do you pull it?

**Pull request closed without merging**
